default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [--no-color]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^(mkdocs|.clang-format)
      - id: check-added-large-files

  - repo: https://github.com/BlankSpruce/gersemi-pre-commit
    rev: 0.28.1
    hooks:
    - id: gersemi
      name: CMake linting
  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v22.1.8
    hooks:
      - id: clang-format
        types_or: [c++, c, proto]
  # Check linting and style issues
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.16.5"
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix, --show-fixes]
      # Run the formatter.
      - id: ruff-format
        exclude: ^(docs)

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.3
    hooks:
      - id: codespell
        exclude: ^(pyproject.toml)

  - repo: https://github.com/fsfe/reuse-tool
    rev: v6.2.0
    hooks:
      - id: reuse-lint-file

  - repo: local
    hooks:
      - id: reuse-annotate
        name: reuse-annotate
        entry: reuse annotate -l MIT --merge-copyrights --single-line -c "Mathis Logemann <mathis@quite.rocks>"
        types_or: [c++, qml, proto, cmake, python, pyi]
        pass_filenames: true
        language: system
        stages: [ manual ]
