site_name: quite
site_url: https://github.com/mathisloge/quite/
site_author: Mathis Logemann

repo_name: mathisloge/quite
repo_url: https://github.com/mathisloge/quite/
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2024 - 2025 Mathis Logemann

theme:
  name: material
  logo: favicon.svg
  favicon: favicon.svg
  palette:
    scheme: slate
    primary: black
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - navigation.top
    - navigation.tabs
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

site_dir: ../build/public

nav:
  - Home: index.md
  - Documentation:
    - Installation: getting-started.md
    - Probe setup: probe-setup.md
    - Python usage: python-usage.md
    - Building: building.md
  - Community:
    - Contributing: contributing.md
  - Blog:
    - blog/index.md

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - blog
  - social
  - privacy:
      enabled: !ENV [CI, false]

extra:
  version:
    provider: mike
