site_name: quite
site_url: https://github.com/mathisloge/ng-quite
site_author: Mathis Logemann

repo_name: mathisloge/ng-quite
repo_url: https://github.com/mathisloge/ng-quite

theme:
  name: material
  features:
  - announce.dismiss
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow

site_dir: ../build/public


plugins:
  - search
  - mkdoxy:
      projects:
        quite:
          src-dirs: libs
          full-doc: True
          doxy-cfg: # standard doxygen configuration (key: value)
            FILE_PATTERNS: "*.cpp *.h*" # specify file patterns to filter out
            RECURSIVE: True # recursive search in source directories
