authors:
  mathisloge:
    name: Mathis Logemann
    description: Maintainer
    avatar: https://avatars.githubusercontent.com/u/13556116?s=400&u=cc177a73e0be6b618719deb6310d016f843416ab&v=4
    slug: https://github.com/mathisloge/
    url: https://github.com/mathisloge/
