name: Build and test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read # access to check out code and install dependencies

jobs:
  format-source-code:
    name: Format source code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - uses: pre-commit/action@v3.0.1
    - uses: pre-commit-ci/lite-action@v1.1.0
      if: always()

  build_matrix:
    strategy:
      matrix:
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    name: Build & Test
    needs: format-source-code
    steps:
      - uses: actions/checkout@v4

      - uses: lukka/get-cmake@latest

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: ninja-build doxygen libunwind-dev libgrpc++-dev protobuf-compiler-grpc
          version: 1.0

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          cache: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements-dev.txt

      - name: Setup headless display
        uses: pyvista/setup-headless-display-action@v4
        with:
          pyvista: false

      - name: Run workflow
        run: cmake --workflow ci
