name: Build and test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  VCPKG_BINARY_SOURCES: clear;x-gha,readwrite
  VCPKG_RELEASE: 2024.06.15
  VCPKG_HOME: vcpkg/
  
jobs:
  format-source-code:
    name: Format source code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - uses: pre-commit/action@v3.0.1
    - uses: pre-commit-ci/lite-action@v1.0.2
      if: always()

  build:
    name: Buid & Test
    runs-on: ${{ matrix.os }}
    needs: format-source-code

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Checkout vcpkg
        uses: actions/checkout@v4
        with:
          path: vcpkg
          ref: ${{ env.VCPKG_RELEASE }}
          repository: microsoft/vcpkg

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      - name: Install required system packages
        shell: bash
        run: |
          if [ "${RUNNER_OS}" == "Linux" ]; then
            sudo apt-get update
            sudo apt-get -y install \
              ninja-build \
              qt6-base-dev
          elif [ "${RUNNER_OS}" == "macOS" ]; then
            brew install \
              ninja
          elif [ "${RUNNER_OS}" == "Windows" ]; then
            choco install \
              ninja
          fi
      - name: Build
        run: > 
          cmake --preset developer-gcc
