name: Build and test

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

permissions:
  contents: read # access to check out code and install dependencies

jobs:
  format-source-code:
    name: Format source code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
    - uses: pre-commit/action@v3.0.1
    - uses: pre-commit-ci/lite-action@v1.1.0
      if: always()

  build_matrix:
    strategy:
      matrix:
        os: [ubuntu-24.04]
        qt-version: [6.5.*, 6.8.*]
    runs-on: ${{ matrix.os }}
    name: Build & Test
    needs: format-source-code
    steps:
      - uses: actions/checkout@v5

      - uses: lukka/get-cmake@latest

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: ninja-build doxygen libunwind-dev libgrpc++-dev protobuf-compiler-grpc weston ccache
          version: 1.0

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.os }}
          create-symlink: true

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          cache: true
          cache-key-prefix: "install-qt-action-${{ matrix.qt-version }}"
          version: ${{ matrix.qt-version }}

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements-dev.txt

      - name: Start Weston
        run: |
          weston --no-config --socket=wl-test-env --backend=headless --idle-time=0 > weston.log 2>&1 &
          # Wait for the Wayland socket to become available (timeout after 10s)
          for i in {1..100}; do
            if [ -e /run/user/$(id -u)/wayland-0 ] || [ -e /tmp/wayland-wl-test-env ]; then
              break
            fi
            sleep 0.1
          done

      - name: Run CMake workflow
        run: cmake --workflow ci
