name: Build and test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read # access to check out code and install dependencies

jobs:
  format-source-code:
    name: Format source code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - uses: pre-commit/action@v3.0.1
    - uses: pre-commit-ci/lite-action@v1.1.0
      if: always()

  build_matrix:
    strategy:
      matrix:
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    name: Build & Test
    needs: format-source-code
    steps:
      - uses: actions/checkout@v4

      - uses: lukka/get-cmake@latest

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: ninja-build doxygen libunwind-dev libgrpc++-dev protobuf-compiler-grpc weston ccache build-essential libgl1-mesa-dev libgstreamer-gl1.0-0 libpulse-dev libxcb-glx0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-render0 libxcb-shape0 libxcb-shm0 libxcb-sync1 libxcb-util1 libxcb-xfixes0 libxcb-xinerama0 libxcb1 libxkbcommon-dev libxkbcommon-x11-0 libxcb-xkb-dev libxcb-cursor0
          version: 1.0

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.os }}
          create-symlink: true

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          cache: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements-dev.txt

      - name: Start Weston
        run: |
          weston --no-config --socket=wl-test-env --backend=headless --idle-time=0 > weston.log 2>&1 &
          # Wait for the Wayland socket to become available (timeout after 10s)
          for i in {1..100}; do
            if [ -e /run/user/$(id -u)/wayland-0 ] || [ -e /tmp/wayland-wl-test-env ]; then
              break
            fi
            sleep 0.1
          done

      - name: Run CMake workflow
        run: cmake --workflow ci
