name: Build and test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  
jobs:
  format-source-code:
    name: Format source code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - uses: pre-commit/action@v3.0.1
    - uses: pre-commit-ci/lite-action@v1.1.0
      if: always()

  build_matrix:
    strategy:
      matrix:
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    name: Buid & Test
    needs: format-source-code
    steps:
      - uses: lukka/get-cmake@latest

      - name: Install Qt
        uses: jurplel/install-qt-action@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements-dev.txt

      - uses: actions/checkout@v4

      - name: Install required system packages
        shell: bash
        run: |
          if [ "${RUNNER_OS}" == "Linux" ]; then
            sudo apt update
            sudo apt -y install \
              ninja-build libgrpc++-dev protobuf-compiler-grpc
          elif [ "${RUNNER_OS}" == "macOS" ]; then
            brew install \
              ninja
          elif [ "${RUNNER_OS}" == "Windows" ]; then
            choco install \
              ninja
          fi
  
      - name: Run workflow
        run: cmake --workflow ci
