name: docs
on:
  push:
    branches:
      - develop
  release:
    types: [published]

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: quite-docs-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            quite-docs-
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: doxygen
          version: 1.0
      - run: pip install -r requirements-dev.txt

      - name: Deploy to develop
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        run: mike deploy --push develop

      - name: Deploy on release
        if: github.event_name == 'release'
        run: mike deploy --push ${{ github.event.release.tag_name }} --update-aliases latest
